// Copyright 2024 QMK -- generated source code only, image retains original copyright
// SPDX-License-Identifier: GPL-2.0-or-later

// This file was auto-generated by `painter_convert_graphics` with arguments:
//    format | pal16
//    output | graphics
//    input  | large_nyan_cat.gif

#pragma once

#include <qp.h>

extern const uint32_t gfx_large_nyan_cat_length;
extern const uint8_t  gfx_large_nyan_cat[24511];
