OLED_ENABLE = yes
MOUSEKEY_ENABLE = yes
SPACE_CADET_ENABLE = no
ENCODER_ENABLE = no
MAGIC_ENABLE = no
GRAVE_ESC_ENABLE = no
KEY_LOCK_ENABLE = no
NKRO_ENABLE = yes
WPM_ENABLE = yes
SPLIT_KEYBOARD = no

RGBLIGHT_ENABLE = yes
RGB_MATRIX_ENABLE = no
